# Array Processing with NumPy

In [1]:
import numpy as np

## Create an Array
Write a Python program that creates an integer array with 4 elements of type unsigned int16 and prints the shape, the number of dimensions, and the length of each element in bytes.

In [3]:
arr = np.array([10, 20, 30, 40], dtype=np.uint16)

# Print the shape of the array
print("Shape:", arr.shape)

# Print the number of dimensions of the array
print("Number of dimensions:", arr.ndim)

# Print the length of each element in bytes
print("Length of each element (in bytes):", arr.itemsize)


Shape: (4,)
Number of dimensions: 1
Length of each element (in bytes): 2


## Create a 2D Array
Write a Python program that creates a $ 5 \times 2 $ integer array from a range between 100 to 200 such that the difference between each element is 10.

In [2]:
#Create 2D array

arr_2 = np.arange(100, 200, 10).reshape(5, 2)

#Display the array
print(arr_2)


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Select Rows and Columns
Write a Python program to return the 2D array of odd rows and even columns from the given numpy array.

In [5]:
# Option 1

# Create a numpy array
arr_3 = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

# Display the 2D array of odd and even numbers
print(f"2D array of odd rows and even columns from the given numpy array: \n", arr_3)

2D array of odd rows and even columns from the given numpy array: 
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [6]:
#Option 2

def get_odd_rows_even_cols(arr):
    return arr[1::2, ::2]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
result = get_odd_rows_even_cols(arr)

print(result)


[[ 5  7]
 [13 15]]


## Compute Numerical Operations
Write a Python program that computes the sum, the element-wise multiplication, and the matrix multiplication of the given numpy arrays. 

In [38]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])
print(a, '\n\n', b)

[[ 5  6]
 [21 18]] 

 [[15 33]
 [ 4  7]]


In [39]:
#sum of the arrays
c = a + b
print("Sum of arrays:\n", c)

# element-wise multiplication of the arrays
d = a * b
print("\nElement-wise multiplication of arrays:\n", d)

# matrix multiplication of the arrays
e = np.dot(a, a)
print("\nMatrix multiplication of arrays:\n", e)

Sum of arrays:
 [[20 39]
 [25 25]]

Element-wise multiplication of arrays:
 [[ 75 198]
 [ 84 126]]

Matrix multiplication of arrays:
 [[151 138]
 [483 450]]


## Split and Concatenate an Array
Write a Python program to split the given $ 8 \times 3 $ array into 4 equal-sized $ 2 \times 3 $ sub-arrays. Then, concatenate the splitted arrays vertically to rebuilt the original array.

In [17]:
# Creating an 8x3 array
arr_5 = np.arange(10, 34, 1).reshape(8, 3)

print("Original array:")
print(arr_5)

Original array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [18]:
# Splitting the array into 4 equal-sized 2x3 sub-arrays
sub_arrays = np.split(arr_5, 4)
print("\nSub-arrays:")
for sub_arr in sub_arrays:
    print(sub_arr)

# Concatenating the sub-arrays vertically to rebuild the original array
con_arr = np.concatenate(sub_arrays, axis=0)
print("\nRebuilt array:")
print(con_arr)



Sub-arrays:
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]

Rebuilt array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


## Replace a Column
Write a Python program that replaces the second column from the given array with the new given column.

In [22]:
arr_6 = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]) 
new_column = np.array([[10, 10, 10]])
arr_6, new_column

(array([[34, 43, 73],
        [82, 22, 12],
        [53, 94, 66]]),
 array([[10, 10, 10]]))

In [23]:
# replace the second column with the new column
arr_6[:, 1] = new_column

print(arr_6)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


## Sort Rows and Columns
Write a Python program to sort the given 2D array in 2 scenarios: (1) Sort the rows; (2) Sort the columns.  

In [25]:
arr_7 = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
arr_7

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [29]:
# sort the rows
sorted_rows = np.sort(arr_7, axis=0)
print(f"Sorted rows:\n", sorted_rows)

print('\n\n')

# sort the columns
sorted_cols = np.sort(arr_7, axis=1)
print(f"Sorted columns:\n", sorted_cols)

Sorted rows:
 [[34 22 12]
 [53 43 66]
 [82 94 73]]



Sorted columns:
 [[34 43 73]
 [12 22 82]
 [53 66 94]]
